name: smoketest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install
          npm run build
          tsc -p tsconfig.spec.json
          npm run pack-copy-template-dirs
          cd dist
          ls -l
          cd ..
          jasmine dist/**/*.spec.js
          npm run pack
          cd dist
          ls -l
          cd ..
